### ISSUE TITLE
minikube is not detected

### ISSUE THREAD

**Issue by changsijay** [vvbogdanov87/gnome-shell-extension-kubeconfig#25]
as `cat ~/.kube/config | grep "\- cluster"` I got 3 lines,
which one of them is minikube.

but in the dropdown, i cannot see minikube

**Comment by vvbogdanov87** [comment]
Could you share your config with obscured creds and URLs?

**Comment by changsijay** [comment]
yes sure

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxx
    server: https://34.126.95.46
  name: gke_o-production
- cluster:
    certificate-authority-data: xxxxx
    server: https://35.240.179.77
  name: gke_o-staging
- cluster:
    certificate-authority: /data/minikube/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Fri, 29 Apr 2022 01:25:17 +07
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: cluster_info
    server: https://192.168.59.106:8443
  name: minikube
contexts:
- context:
    cluster: gke_o-production
    namespace: integrations
    user: gke_o-production
  name: gke_o-production
- context:
    cluster: gke_o-staging
    namespace: integrations
    user: gke_o-staging
  name: gke_o-staging
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Fri, 29 Apr 2022 01:25:17 +07
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: gke_o-production
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /data/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_o-staging
  user:
    auth-provider:
      config:
        access-token: xxxxx
        cmd-args: config config-helper --format=json
        cmd-path: /home/csj/google-cloud-sdk/bin/gcloud
        expiry: "2022-04-28T08:21:42Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: minikube
  user:
    client-certificate: /data/minikube/.minikube/profiles/minikube/client.crt
    client-key: /data/minikube/.minikube/profiles/minikube/client.key
```
