### ISSUE TITLE
Contexts are not displayed in dropdown

### ISSUE THREAD

**Issue by anthonyrichir** [vvbogdanov87/gnome-shell-extension-kubeconfig#3]
Hello,

I only see the current context and none of the context from my ~/.kube/config are available in the dropdown although I have multiple contexts.
![image](https://user-images.githubusercontent.com/5638857/53597684-146e6d00-3ba3-11e9-88d2-8022cffefd84.png)
```yaml
apiVersion: v1
clusters:
...
contexts:
- context:
    cluster: work-local
    namespace: team-int
    user: ...
  name: integration-team
- context:
    cluster: work-local
    namespace: logging
    user: ...
  name: local-logging
- context:
    cluster: microk8s-cluster
    namespace: project
    user: ...
  name: microk8s
- context:
    cluster: work-local
    namespace: rundeck
    user: ...
  name: rundeck-local
current-context: microk8s
kind: Config
preferences: {}
users:
...
```
Note that if I change the current context, the extension displays the new value.
Is there something wrong with my config file ?
